### ISSUE TITLE
[BUG] Fix CSS property typo

### ISSUE THREAD

**Issue by Krenodeno** [wanadev/PhotonUI#174]
https://github.com/wanadev/PhotonUI/blob/a678948de9fdc35453a8b1dd0c12c7d366700939/less/base/interactive/slider.less#L35

```css
    flew-wrap: nowrap;
```

is written, instead of 

```css
    flex-wrap: nowrap;
```

**Comment by jbghoul-wanadev** [comment]
solved by https://github.com/wanadev/PhotonUI/pull/173

**Comment by Krenodeno** [comment]
So it lacks being merged to default branch and tagged. Thanks !
