### ISSUE TITLE
Did you use PhotonUI to design the menus of WannaPlan?

### ISSUE THREAD

**Issue by Abdelkrim** [wanadev/PhotonUI#20]
to whom it may concern,
did you use PhotonUI to design the following widgets: top-right menus, zoom, menu and submenus etc.

thank you for your feedback

![wannaplan](https://cloud.githubusercontent.com/assets/791663/10590194/b60f8016-76af-11e5-972e-e241b312eff9.PNG)

**Comment by flozz** [comment]
Hello,

no, Wanaplan does not use PhotonUI in its main UI yet (but it will use it soon).
