### ISSUE TITLE
What is type : kzd.Color

### ISSUE THREAD

**Issue by MangelMaxime** [wanadev/PhotonUI#24]
Hello guys, I am working on a definition library for PhotonUI. 

And I just encounter something strange.

All the Color widget:
* ColorPalette
* ColorButton
* ColorPickerDialog
* ColorPicker

Have a property `_color` of type `kzd.Color`. I don't really understand this type. For example : [Here](https://github.com/wanadev/PhotonUI/blob/d551b1b6142998771362c3dfd82fe90996c0d57f/src/interactive/colorpalette.js#L91)

I was thinking that this widgets should use the type `photonui.Color = require("./nonvisual/color.js");`

**Comment by flozz** [comment]
Oops...

You are right, those widgets uses `photonui.Color`... That's an error in the doc, I will fixed it on `develop`.

Thanks!

_The `Color*` widgets were first developed in a project called [Kazadecor](http://kazadecor.net/demo.html) and I forget to update the doc when I imported the widgets in PhotonUI..._

**Comment by MangelMaxime** [comment]
Thanks for the answer :)
