### ISSUE TITLE
Fluid Layout : End line too much spacing

### ISSUE THREAD

**Issue by MangelMaxime** [wanadev/PhotonUI#33]
When we have a FluidLayout with severals items and we are on the edge of placing the last widget of a line to the next one, the spacing here is too wide.

It's should be like on the left side.

Here is a screen with the problem shown:
![2016-04-25_1708](https://cloud.githubusercontent.com/assets/4760796/14788798/eacfd2c6-0b09-11e6-81dc-f1e715c5ea27.png)

**Comment by flozz** [comment]
Fixed in PhotonUI 1.4.1
