### ISSUE TITLE
ColorPickerDialog : value params is ignored

### ISSUE THREAD

**Issue by MangelMaxime** [wanadev/PhotonUI#39]
This [sample](http://wanadev.github.io/PhotonUI/doc/widgets/colorpickerdialog.html) is setting a default value to the ColorPickerDialog but when you first open the Dialog, it's always the red that is selected. 

So the `value` params is ignored.

**Comment by flozz** [comment]
The `value` parameter does not even exists in the code.... I will add it for consistency with other widgets...
