### ISSUE TITLE
photonui.Slider: the visible property has no effect

### ISSUE THREAD

**Issue by flozz** [wanadev/PhotonUI#40]
Nothing happen when setting the `visible` property of the `photonui.Slider`to `false`. This is caused by a `display: flex !important;` in the CSS...

Example code to reproduce:

```javascript
var slider = new photonui.Slider({
    fieldVisible: true,
    min: 0, max: 100,
    step: 10,
    value: 50,
    visible: false
 });
```

Expected: Slider should not be displayed.
Current Result: The slider is visible.

**Comment by MangelMaxime** [comment]
I just made some really little test and why not just removing the `!important` in the CSS ?

By removing it it's working as expected. I just tested it with nothing fancy for the moment.

**Comment by flozz** [comment]
If my memory is good, the `!important` was added because one of the layouts break the slider by overriding the display property of its children...

**Comment by flozz** [comment]
It is the `BoxLayout` → https://github.com/wanadev/PhotonUI/blob/master/less/base/layout/boxlayout.less#L57

But it does this for a good reason too... I will have to make some tests to fix that...
