### ISSUE TITLE
Closing a Window with an opened Select does not hide the selecting Menu

### ISSUE THREAD

**Issue by Breush** [wanadev/PhotonUI#78]
See [example on JSFiddle](https://jsfiddle.net/tmLsvfy2/2/).

![screenshot_1](https://cloud.githubusercontent.com/assets/8821452/19926244/c95b1e68-a0f3-11e6-8b63-c75a048b6608.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/8821452/19926245/c95db4e8-a0f3-11e6-92f2-d0e0b59be7c9.png)

**Comment by flozz** [comment]
fixed by https://github.com/wanadev/PhotonUI/pull/152
